name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    # Add this step to log in to Docker Hub
    # You will need to add DOCKERHUB_USERNAME and DOCKERHUB_TOKEN as secrets to your GitHub repository
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./Dockerfile
        # This will push the image to Docker Hub
        push: true
        # Replace 'your-dockerhub-username' with your Docker Hub username
        tags: your-dockerhub-username/chatbot-ai:latest
        # This ensures the image is built with the older Docker v2 manifest format
        provenance: false
